/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin/unauthorized'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUnitesIndexRouteImport } from './routes/admin/unites/index'
import { Route as AdminStocksIndexRouteImport } from './routes/admin/stocks/index'
import { Route as AdminProduitsIndexRouteImport } from './routes/admin/produits/index'
import { Route as AdminFacturesIndexRouteImport } from './routes/admin/factures/index'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminFacturesFactureIdRouteImport } from './routes/admin/factures/$factureId'
import { Route as AdminAbonnementsSuccessRouteImport } from './routes/admin/abonnements/success'
import { Route as AdminAbonnementsCancelRouteImport } from './routes/admin/abonnements/cancel'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitesIndexRoute = AdminUnitesIndexRouteImport.update({
  id: '/unites/',
  path: '/unites/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocksIndexRoute = AdminStocksIndexRouteImport.update({
  id: '/stocks/',
  path: '/stocks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsIndexRoute = AdminProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturesIndexRoute = AdminFacturesIndexRouteImport.update({
  id: '/factures/',
  path: '/factures/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturesFactureIdRoute = AdminFacturesFactureIdRouteImport.update({
  id: '/factures/$factureId',
  path: '/factures/$factureId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsSuccessRoute = AdminAbonnementsSuccessRouteImport.update({
  id: '/abonnements/success',
  path: '/abonnements/success',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbonnementsCancelRoute = AdminAbonnementsCancelRouteImport.update({
  id: '/abonnements/cancel',
  path: '/abonnements/cancel',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/abonnements/cancel': typeof AdminAbonnementsCancelRoute
  '/admin/abonnements/success': typeof AdminAbonnementsSuccessRoute
  '/admin/factures/$factureId': typeof AdminFacturesFactureIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/factures': typeof AdminFacturesIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/admin/stocks': typeof AdminStocksIndexRoute
  '/admin/unites': typeof AdminUnitesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/register': typeof RegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin': typeof AdminIndexRoute
  '/admin/abonnements/cancel': typeof AdminAbonnementsCancelRoute
  '/admin/abonnements/success': typeof AdminAbonnementsSuccessRoute
  '/admin/factures/$factureId': typeof AdminFacturesFactureIdRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/factures': typeof AdminFacturesIndexRoute
  '/admin/produits': typeof AdminProduitsIndexRoute
  '/admin/stocks': typeof AdminStocksIndexRoute
  '/admin/unites': typeof AdminUnitesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/abonnements/cancel': typeof AdminAbonnementsCancelRoute
  '/admin/abonnements/success': typeof AdminAbonnementsSuccessRoute
  '/admin/factures/$factureId': typeof AdminFacturesFactureIdRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/factures/': typeof AdminFacturesIndexRoute
  '/admin/produits/': typeof AdminProduitsIndexRoute
  '/admin/stocks/': typeof AdminStocksIndexRoute
  '/admin/unites/': typeof AdminUnitesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/admin'
    | '/register'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/abonnements/cancel'
    | '/admin/abonnements/success'
    | '/admin/factures/$factureId'
    | '/admin/clients'
    | '/admin/factures'
    | '/admin/produits'
    | '/admin/stocks'
    | '/admin/unites'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/register'
    | '/admin/unauthorized'
    | '/admin'
    | '/admin/abonnements/cancel'
    | '/admin/abonnements/success'
    | '/admin/factures/$factureId'
    | '/admin/clients'
    | '/admin/factures'
    | '/admin/produits'
    | '/admin/stocks'
    | '/admin/unites'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/admin'
    | '/register'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/abonnements/cancel'
    | '/admin/abonnements/success'
    | '/admin/factures/$factureId'
    | '/admin/clients/'
    | '/admin/factures/'
    | '/admin/produits/'
    | '/admin/stocks/'
    | '/admin/unites/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AdminRoute: typeof AdminRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unites/': {
      id: '/admin/unites/'
      path: '/unites'
      fullPath: '/admin/unites'
      preLoaderRoute: typeof AdminUnitesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stocks/': {
      id: '/admin/stocks/'
      path: '/stocks'
      fullPath: '/admin/stocks'
      preLoaderRoute: typeof AdminStocksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produits/': {
      id: '/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AdminProduitsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factures/': {
      id: '/admin/factures/'
      path: '/factures'
      fullPath: '/admin/factures'
      preLoaderRoute: typeof AdminFacturesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factures/$factureId': {
      id: '/admin/factures/$factureId'
      path: '/factures/$factureId'
      fullPath: '/admin/factures/$factureId'
      preLoaderRoute: typeof AdminFacturesFactureIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements/success': {
      id: '/admin/abonnements/success'
      path: '/abonnements/success'
      fullPath: '/admin/abonnements/success'
      preLoaderRoute: typeof AdminAbonnementsSuccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abonnements/cancel': {
      id: '/admin/abonnements/cancel'
      path: '/abonnements/cancel'
      fullPath: '/admin/abonnements/cancel'
      preLoaderRoute: typeof AdminAbonnementsCancelRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAbonnementsCancelRoute: typeof AdminAbonnementsCancelRoute
  AdminAbonnementsSuccessRoute: typeof AdminAbonnementsSuccessRoute
  AdminFacturesFactureIdRoute: typeof AdminFacturesFactureIdRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminFacturesIndexRoute: typeof AdminFacturesIndexRoute
  AdminProduitsIndexRoute: typeof AdminProduitsIndexRoute
  AdminStocksIndexRoute: typeof AdminStocksIndexRoute
  AdminUnitesIndexRoute: typeof AdminUnitesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAbonnementsCancelRoute: AdminAbonnementsCancelRoute,
  AdminAbonnementsSuccessRoute: AdminAbonnementsSuccessRoute,
  AdminFacturesFactureIdRoute: AdminFacturesFactureIdRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminFacturesIndexRoute: AdminFacturesIndexRoute,
  AdminProduitsIndexRoute: AdminProduitsIndexRoute,
  AdminStocksIndexRoute: AdminStocksIndexRoute,
  AdminUnitesIndexRoute: AdminUnitesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AdminRoute: AdminRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
